### ISSUE TITLE
Admin\ContactForm - Field `existing_bciers_user` displays after creating a new contact

### ISSUE THREAD

**Issue by shon-button** [bcgov/cas-registration#2092]
Describe the Bug:

Admin\ContactForm field `existing_bciers_user` displays after creating a new contact but should only display on new form.
![image](https://github.com/user-attachments/assets/29724cbe-5a2b-43e0-8992-a8be6d724b93)

Seemingly, the after `ContactForm` create/submit the `ContactPage` parameter `schema={createContactSchema(userOperatorUsers, isCreating)}` still computes as create.
![image](https://github.com/user-attachments/assets/8ab85a64-090e-40dc-9fce-3a984d0ea1ff)

Probability (how likely the bug is to happen, scored from 1-5):
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5):
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:

Screenshots:

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by Sepehr-Sobhani** [comment]
@shon-button I'm curious why the following line of code in `createContactSchema.tsx` isn't working?
```typescript
...
  } else {
    delete localSchema.properties.section1.properties.existing_bciers_user;
    delete localSchema.properties.section1.allOf;
  }
...
```

**Comment by BCerki** [comment]
@shon-button , I'm not able to reproduce this: https://www.loom.com/share/5d010892a279493a8c7df730780b5127. Maybe it got fixed in some of the work @Sepehr-Sobhani  was doing with the Operation Representative form?

**Comment by Sepehr-Sobhani** [comment]
@BCerki To replicate this issue, create a new contact. After submitting the form, you will still see 'existing_bciers_user'(in read-only format) but it disappears upon refreshing the page.

**Comment by patriciarussellCAS** [comment]
Are we still using the "Is this contact a user in BCIERS" toggle? I feel like I heard this was taken out, but may be mis-remembering.

**Comment by patriciarussellCAS** [comment]
I'm unable to recreate this issue - has this been resolved? @Sepehr-Sobhani or @BCerki

**Comment by BCerki** [comment]
> I'm unable to recreate this issue - has this been resolved? @Sepehr-Sobhani or @BCerki

It should be resolved! I put in a fix three weeks ago: https://github.com/bcgov/cas-registration/pull/2187
